import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='lg:dark:bg-zinc-800/30 dark:bg-gray-900'>
        <Navbar />
         <div className="">
         {children}
         
         </div>
      </body>
    </html>
  );
}
